git-1_sample_repo: com.tia.bmm.server.theatre.Theatre Class Reference
com.tia.bmm.server.theatre.Theatre Class Reference
Public Member Functions
Theatre ()
String getTheatreName ()
void setTheatreName (String theatreName)
List< Movie > getMovies ()
void setMovies (List< Movie > movies)
Data Fields
int theatreId
Address address
Package Functions
Theatre (int tid, String n, Address add)
Private Attributes
String theatreName
List< Movie > movies = new ArrayList<Movie>()
Constructor & Destructor Documentation
Theatre() [1/2]
com.tia.bmm.server.theatre.Theatre.Theatre () inline
Theatre() [2/2]
com.tia.bmm.server.theatre.Theatre.Theatre (int tid, String n, Address add) inline package
Member Function Documentation
getMovies()
List<Movie> com.tia.bmm.server.theatre.Theatre.getMovies () inline
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), com.tia.bmm.server.theatre.TheatreList.displayMoviesInTheatre(), and com.tia.bmm.server.booking.Booking.handleBooking().
getTheatreName()
String com.tia.bmm.server.theatre.Theatre.getTheatreName () inline
Referenced by com.tia.bmm.server.theatre.TheatreList.displayMoviesInTheatre(), com.tia.bmm.server.theatre.TheatreList.displayTheatre(), com.tia.bmm.server.theatre.TheatreList.displayTheatreList(), and com.tia.bmm.server.booking.Booking.handleBooking().
setMovies()
void com.tia.bmm.server.theatre.Theatre.setMovies (List< Movie > movies) inline
setTheatreName()
void com.tia.bmm.server.theatre.Theatre.setTheatreName (String theatreName) inline
Referenced by com.tia.bmm.server.theatre.Theatre.Theatre().
Field Documentation
address
Address com.tia.bmm.server.theatre.Theatre.address
Referenced by com.tia.bmm.server.theatre.TheatreList.displayTheatre(), com.tia.bmm.server.theatre.TheatreList.displayTheatreList(), com.tia.bmm.server.booking.Booking.handleBooking(), and com.tia.bmm.server.theatre.Theatre.Theatre().
movies
List<Movie> com.tia.bmm.server.theatre.Theatre.movies = new ArrayList<Movie>() private
Referenced by com.tia.bmm.server.theatre.Theatre.getMovies(), and com.tia.bmm.server.theatre.Theatre.setMovies().
theatreId
int com.tia.bmm.server.theatre.Theatre.theatreId
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), com.tia.bmm.server.theatre.TheatreList.checkTheatreIdPresent(), com.tia.bmm.server.theatre.TheatreList.displayTheatre(), com.tia.bmm.server.theatre.TheatreList.displayTheatreList(), com.tia.bmm.server.booking.Booking.handleBooking(), com.tia.bmm.server.theatre.TheatreList.removeTheatre(), and com.tia.bmm.server.theatre.Theatre.Theatre().
theatreName
String com.tia.bmm.server.theatre.Theatre.theatreName private
Referenced by com.tia.bmm.server.theatre.Theatre.getTheatreName(), and com.tia.bmm.server.theatre.Theatre.setTheatreName().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/theatre/Theatre.java