git-1_sample_repo: com.tia.bmm.server.address.Address Class Reference
com.tia.bmm.server.address.Address Class Reference
Public Member Functions
Address ()
Address addAddress ()
void displayAddress (Address a)
String getStreetNo ()
void setStreetNo (String streetNo)
String getLandmark ()
void setLandmark (String landmark)
String getCity ()
void setCity (String city)
String getPinCode ()
void setPinCode (String pinCode)
String getState ()
void setState (String state)
Package Functions
Address (String c, String p, String st, String sn, String lm)
Private Attributes
String city
String pinCode
String state
String streetNo
String landmark
Constructor & Destructor Documentation
Address() [1/2]
com.tia.bmm.server.address.Address.Address () inline
Referenced by com.tia.bmm.server.address.Address.addAddress().
Address() [2/2]
com.tia.bmm.server.address.Address.Address (String c, String p, String st, String sn, String lm) inline package
Member Function Documentation
addAddress()
Address com.tia.bmm.server.address.Address.addAddress () inline
Referenced by com.tia.bmm.server.theatre.TheatreList.addTheatre().
displayAddress()
void com.tia.bmm.server.address.Address.displayAddress (Address a) inline
Referenced by com.tia.bmm.server.theatre.TheatreList.displayTheatre(), and com.tia.bmm.server.theatre.TheatreList.displayTheatreList().
getCity()
String com.tia.bmm.server.address.Address.getCity () inline
Referenced by com.tia.bmm.server.address.Address.displayAddress(), and com.tia.bmm.server.booking.Booking.handleBooking().
getLandmark()
String com.tia.bmm.server.address.Address.getLandmark () inline
Referenced by com.tia.bmm.server.address.Address.displayAddress(), and com.tia.bmm.server.booking.Booking.handleBooking().
getPinCode()
String com.tia.bmm.server.address.Address.getPinCode () inline
Referenced by com.tia.bmm.server.address.Address.displayAddress(), and com.tia.bmm.server.booking.Booking.handleBooking().
getState()
String com.tia.bmm.server.address.Address.getState () inline
Referenced by com.tia.bmm.server.address.Address.displayAddress(), and com.tia.bmm.server.booking.Booking.handleBooking().
getStreetNo()
String com.tia.bmm.server.address.Address.getStreetNo () inline
Referenced by com.tia.bmm.server.address.Address.displayAddress(), and com.tia.bmm.server.booking.Booking.handleBooking().
setCity()
void com.tia.bmm.server.address.Address.setCity (String city) inline
Referenced by com.tia.bmm.server.address.Address.Address().
setLandmark()
void com.tia.bmm.server.address.Address.setLandmark (String landmark) inline
Referenced by com.tia.bmm.server.address.Address.Address().
setPinCode()
void com.tia.bmm.server.address.Address.setPinCode (String pinCode) inline
Referenced by com.tia.bmm.server.address.Address.Address().
setState()
void com.tia.bmm.server.address.Address.setState (String state) inline
Referenced by com.tia.bmm.server.address.Address.Address().
setStreetNo()
void com.tia.bmm.server.address.Address.setStreetNo (String streetNo) inline
Referenced by com.tia.bmm.server.address.Address.Address().
Field Documentation
city
String com.tia.bmm.server.address.Address.city private
Referenced by com.tia.bmm.server.address.Address.getCity(), and com.tia.bmm.server.address.Address.setCity().
landmark
String com.tia.bmm.server.address.Address.landmark private
Referenced by com.tia.bmm.server.address.Address.getLandmark(), and com.tia.bmm.server.address.Address.setLandmark().
pinCode
String com.tia.bmm.server.address.Address.pinCode private
Referenced by com.tia.bmm.server.address.Address.getPinCode(), and com.tia.bmm.server.address.Address.setPinCode().
state
String com.tia.bmm.server.address.Address.state private
Referenced by com.tia.bmm.server.address.Address.getState(), and com.tia.bmm.server.address.Address.setState().
streetNo
String com.tia.bmm.server.address.Address.streetNo private
Referenced by com.tia.bmm.server.address.Address.getStreetNo(), and com.tia.bmm.server.address.Address.setStreetNo().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/address/Address.java