git-1_sample_repo: com.tia.bmm.server.movie.Seat Class Reference
com.tia.bmm.server.movie.Seat Class Reference
Public Member Functions
Seat ()
SeatStatus getSeatStatus ()
void setSeatStatus (SeatStatus seatStatus)
int getSeatNo ()
void setSeatNo (int seatNo)
Package Functions
Seat (int sno, SeatType st, SeatStatus ss, float c)
Package Attributes
SeatType seatType
float seatCost
Private Attributes
int seatNo
SeatStatus seatStatus
Constructor & Destructor Documentation
Seat() [1/2]
com.tia.bmm.server.movie.Seat.Seat () inline
Seat() [2/2]
com.tia.bmm.server.movie.Seat.Seat (int sno, SeatType st, SeatStatus ss, float c) inline package
Member Function Documentation
getSeatNo()
int com.tia.bmm.server.movie.Seat.getSeatNo () inline
Referenced by com.tia.bmm.server.booking.Booking.handleBooking().
getSeatStatus()
SeatStatus com.tia.bmm.server.movie.Seat.getSeatStatus () inline
Referenced by com.tia.bmm.server.booking.Booking.handleBooking().
setSeatNo()
void com.tia.bmm.server.movie.Seat.setSeatNo (int seatNo) inline
Referenced by com.tia.bmm.server.movie.Seat.Seat().
setSeatStatus()
void com.tia.bmm.server.movie.Seat.setSeatStatus (SeatStatus seatStatus) inline
Referenced by com.tia.bmm.server.booking.Booking.handleBooking(), and com.tia.bmm.server.movie.Seat.Seat().
Field Documentation
seatCost
float com.tia.bmm.server.movie.Seat.seatCost package
Referenced by com.tia.bmm.server.movie.Seat.Seat().
seatNo
int com.tia.bmm.server.movie.Seat.seatNo private
Referenced by com.tia.bmm.server.movie.Seat.getSeatNo(), and com.tia.bmm.server.movie.Seat.setSeatNo().
seatStatus
SeatStatus com.tia.bmm.server.movie.Seat.seatStatus private
Referenced by com.tia.bmm.server.movie.Seat.getSeatStatus(), and com.tia.bmm.server.movie.Seat.setSeatStatus().
seatType
SeatType com.tia.bmm.server.movie.Seat.seatType package
Referenced by com.tia.bmm.server.movie.Seat.Seat().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/movie/Seat.java