git-1_sample_repo: com.tia.bmm.server.movie.MovieList Class Reference
com.tia.bmm.server.movie.MovieList Class Reference
Public Member Functions
void addMovie ()
void displayMovieList (TheatreList ob)
Data Fields
List< Movie > Ml = new ArrayList<Movie>()
Static Package Functions
[static initializer]
Static Package Attributes
static int id
Member Function Documentation
[static initializer]()
com.tia.bmm.server.movie.MovieList.[static initializer] inline static package
addMovie()
void com.tia.bmm.server.movie.MovieList.addMovie () inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
displayMovieList()
void com.tia.bmm.server.movie.MovieList.displayMovieList (TheatreList ob) inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
Field Documentation
id
int com.tia.bmm.server.movie.MovieList.id static package
Ml
List<Movie> com.tia.bmm.server.movie.MovieList.Ml = new ArrayList<Movie>()
Referenced by com.tia.bmm.server.movie.MovieList.addMovie(), com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), and com.tia.bmm.server.movie.MovieList.displayMovieList().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/movie/MovieList.java