git-1_sample_repo: com.tia.bmm.server.theatre.TheatreList Class Reference
com.tia.bmm.server.theatre.TheatreList Class Reference
Public Member Functions
void addTheatre ()
void removeTheatre ()
void displayTheatreList ()
void addMovieInTheatre (MovieList obj)
void displayTheatre (int t)
Data Fields
List< Theatre > Tl = new ArrayList<Theatre>()
Package Functions
void displayMoviesInTheatre (Theatre t)
boolean checkTheatreIdPresent (int t)
Static Package Attributes
static int id
static
Member Function Documentation
addMovieInTheatre()
void com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre (MovieList obj) inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
addTheatre()
void com.tia.bmm.server.theatre.TheatreList.addTheatre () inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
checkTheatreIdPresent()
boolean com.tia.bmm.server.theatre.TheatreList.checkTheatreIdPresent (int t) inline package
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre().
displayMoviesInTheatre()
void com.tia.bmm.server.theatre.TheatreList.displayMoviesInTheatre (Theatre t) inline package
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre().
displayTheatre()
void com.tia.bmm.server.theatre.TheatreList.displayTheatre (int t) inline
Referenced by com.tia.bmm.server.movie.MovieList.displayMovieList().
displayTheatreList()
void com.tia.bmm.server.theatre.TheatreList.displayTheatreList () inline
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), and com.tia.bmm.server.main.MainMenu.main().
removeTheatre()
void com.tia.bmm.server.theatre.TheatreList.removeTheatre () inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
Field Documentation
id
int com.tia.bmm.server.theatre.TheatreList.id static package
static
com.tia.bmm.server.theatre.TheatreList.static static package
Initial value:
{
        id = 1
Tl
List<Theatre> com.tia.bmm.server.theatre.TheatreList.Tl = new ArrayList<Theatre>()
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), com.tia.bmm.server.theatre.TheatreList.addTheatre(), com.tia.bmm.server.theatre.TheatreList.checkTheatreIdPresent(), com.tia.bmm.server.theatre.TheatreList.displayTheatre(), com.tia.bmm.server.theatre.TheatreList.displayTheatreList(), and com.tia.bmm.server.theatre.TheatreList.removeTheatre().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/theatre/TheatreList.java