git-1_sample_repo: com.tia.bmm.server.user.UserList Class Reference
com.tia.bmm.server.user.UserList Class Reference
Public Member Functions
void createUser ()
void displayUsers ()
HashMap< Integer, User > getUl ()
void setUl (HashMap< Integer, User > ul)
Package Functions
boolean loginAsUser ()
Static Package Functions
[static initializer]
Static Package Attributes
static int id
Private Attributes
HashMap< Integer, User > Ul = new HashMap<Integer,User>()
Member Function Documentation
[static initializer]()
com.tia.bmm.server.user.UserList.[static initializer] inline static package
createUser()
void com.tia.bmm.server.user.UserList.createUser () inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
displayUsers()
void com.tia.bmm.server.user.UserList.displayUsers () inline
Referenced by com.tia.bmm.server.main.MainMenu.main().
getUl()
HashMap<Integer,User> com.tia.bmm.server.user.UserList.getUl () inline
Referenced by com.tia.bmm.server.user.UserList.createUser(), com.tia.bmm.server.user.UserList.displayUsers(), and com.tia.bmm.server.user.UserList.loginAsUser().
loginAsUser()
boolean com.tia.bmm.server.user.UserList.loginAsUser () inline package
setUl()
void com.tia.bmm.server.user.UserList.setUl (HashMap< Integer, User > ul) inline
Field Documentation
id
int com.tia.bmm.server.user.UserList.id static package
Ul
HashMap<Integer,User> com.tia.bmm.server.user.UserList.Ul = new HashMap<Integer,User>() private
Referenced by com.tia.bmm.server.user.UserList.getUl(), and com.tia.bmm.server.user.UserList.setUl().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/user/UserList.java