git-1_sample_repo: com.tia.bmm.server.movie.Movie Class Reference
com.tia.bmm.server.movie.Movie Class Reference
Public Member Functions
Movie ()
void displayMovie ()
float getRating ()
void setRating (float rating)
int getMovieId ()
void setMovieId (int movieId)
String getMovieName ()
void setMovieName (String movieName)
List< Seat > getShowAtFour ()
void setShowAtFour (List< Seat > showAtFour)
MovieType getMovieType ()
void setMovieType (MovieType movieType)
Data Fields
List< Integer > theaterId = new ArrayList<Integer>()
MovieStatus movieStatus
Package Functions
Movie (int mid, String n, MovieType mt, MovieStatus ms, float r)
Private Attributes
int movieId
String movieName
MovieType movieType
float rating
List< Seat > showAtFour = new ArrayList<Seat>(50)
Constructor & Destructor Documentation
Movie() [1/2]
com.tia.bmm.server.movie.Movie.Movie () inline
Movie() [2/2]
com.tia.bmm.server.movie.Movie.Movie (int mid, String n, MovieType mt, MovieStatus ms, float r) inline package
Member Function Documentation
displayMovie()
void com.tia.bmm.server.movie.Movie.displayMovie () inline
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), and com.tia.bmm.server.theatre.TheatreList.displayMoviesInTheatre().
getMovieId()
int com.tia.bmm.server.movie.Movie.getMovieId () inline
Referenced by com.tia.bmm.server.movie.Movie.displayMovie(), com.tia.bmm.server.movie.MovieList.displayMovieList(), and com.tia.bmm.server.booking.Booking.handleBooking().
getMovieName()
String com.tia.bmm.server.movie.Movie.getMovieName () inline
Referenced by com.tia.bmm.server.movie.Movie.displayMovie(), com.tia.bmm.server.movie.MovieList.displayMovieList(), and com.tia.bmm.server.booking.Booking.handleBooking().
getMovieType()
MovieType com.tia.bmm.server.movie.Movie.getMovieType () inline
Referenced by com.tia.bmm.server.movie.MovieList.displayMovieList(), and com.tia.bmm.server.booking.Booking.handleBooking().
getRating()
float com.tia.bmm.server.movie.Movie.getRating () inline
Referenced by com.tia.bmm.server.movie.MovieList.displayMovieList(), and com.tia.bmm.server.booking.Booking.handleBooking().
getShowAtFour()
List<Seat> com.tia.bmm.server.movie.Movie.getShowAtFour () inline
Referenced by com.tia.bmm.server.booking.Booking.handleBooking(), and com.tia.bmm.server.movie.Movie.Movie().
setMovieId()
void com.tia.bmm.server.movie.Movie.setMovieId (int movieId) inline
Referenced by com.tia.bmm.server.movie.Movie.Movie().
setMovieName()
void com.tia.bmm.server.movie.Movie.setMovieName (String movieName) inline
Referenced by com.tia.bmm.server.movie.Movie.Movie().
setMovieType()
void com.tia.bmm.server.movie.Movie.setMovieType (MovieType movieType) inline
Referenced by com.tia.bmm.server.movie.Movie.Movie().
setRating()
void com.tia.bmm.server.movie.Movie.setRating (float rating) inline
Referenced by com.tia.bmm.server.movie.Movie.Movie().
setShowAtFour()
void com.tia.bmm.server.movie.Movie.setShowAtFour (List< Seat > showAtFour) inline
Field Documentation
movieId
int com.tia.bmm.server.movie.Movie.movieId private
Referenced by com.tia.bmm.server.movie.Movie.getMovieId(), and com.tia.bmm.server.movie.Movie.setMovieId().
movieName
String com.tia.bmm.server.movie.Movie.movieName private
Referenced by com.tia.bmm.server.movie.Movie.getMovieName(), and com.tia.bmm.server.movie.Movie.setMovieName().
movieStatus
MovieStatus com.tia.bmm.server.movie.Movie.movieStatus
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), com.tia.bmm.server.movie.MovieList.displayMovieList(), com.tia.bmm.server.theatre.TheatreList.displayMoviesInTheatre(), com.tia.bmm.server.booking.Booking.handleBooking(), and com.tia.bmm.server.movie.Movie.Movie().
movieType
MovieType com.tia.bmm.server.movie.Movie.movieType private
Referenced by com.tia.bmm.server.movie.Movie.getMovieType(), and com.tia.bmm.server.movie.Movie.setMovieType().
rating
float com.tia.bmm.server.movie.Movie.rating private
Referenced by com.tia.bmm.server.movie.Movie.getRating(), and com.tia.bmm.server.movie.Movie.setRating().
showAtFour
List<Seat> com.tia.bmm.server.movie.Movie.showAtFour = new ArrayList<Seat>(50) private
Referenced by com.tia.bmm.server.movie.Movie.getShowAtFour(), and com.tia.bmm.server.movie.Movie.setShowAtFour().
theaterId
List<Integer> com.tia.bmm.server.movie.Movie.theaterId = new ArrayList<Integer>()
Referenced by com.tia.bmm.server.theatre.TheatreList.addMovieInTheatre(), com.tia.bmm.server.movie.MovieList.displayMovieList(), and com.tia.bmm.server.booking.Booking.handleBooking().
The documentation for this class was generated from the following file:
src/main/resources/testdata/bookMyMovieTia-main/src/com/tia/bmm/server/movie/Movie.java